import { Business, Category } from './types';

export const CITIES = [
  'Mumbai',
  'Delhi',
  'Bengaluru',
  'Chennai',
  'Hyderabad',
  'Pune',
  'Kolkata',
  'Ahmedabad'
];

export const CATEGORIES: Category[] = [
  { id: 'restaurants', name: 'Restaurants', iconName: 'Utensils', count: 480, color: 'from-orange-400 to-red-500' },
  { id: 'doctors', name: 'Doctors', iconName: 'Stethoscope', count: 320, color: 'from-blue-400 to-indigo-500' },
  { id: 'plumbers', name: 'Plumbers', iconName: 'Wrench', count: 180, color: 'from-emerald-400 to-teal-500' },
  { id: 'hotels', name: 'Hotels', iconName: 'Hotel', count: 250, color: 'from-violet-400 to-purple-500' },
  { id: 'education', name: 'Schools & Tutors', iconName: 'GraduationCap', count: 190, color: 'from-cyan-400 to-blue-500' },
  { id: 'salons', name: 'Salons & Spas', iconName: 'Sparkles', count: 290, color: 'from-pink-400 to-rose-500' },
  { id: 'gyms', name: 'Gyms & Fitness', iconName: 'Dumbbell', count: 150, color: 'from-amber-400 to-orange-500' },
  { id: 'rentals', name: 'Car Rentals', iconName: 'Car', count: 110, color: 'from-sky-400 to-indigo-500' },
  { id: 'packers', name: 'Packers & Movers', iconName: 'Truck', count: 85, color: 'from-slate-400 to-slate-600' },
  { id: 'electronics', name: 'Electronics Shops', iconName: 'Laptop', count: 220, color: 'from-teal-400 to-emerald-500' },
  { id: 'hospitals', name: 'Hospitals', iconName: 'HeartPulse', count: 95, color: 'from-red-400 to-rose-500' },
  { id: 'pest-control', name: 'Pest Control', iconName: 'ShieldAlert', count: 70, color: 'from-lime-500 to-emerald-600' }
];

export const INITIAL_BUSINESSES: Business[] = [
  {
    id: 'b1',
    name: 'The Spicy Feast Restaurant',
    category: 'restaurants',
    rating: 4.8,
    reviewsCount: 142,
    address: 'Shop 12, Link Road, Andheri West',
    area: 'Andheri West',
    city: 'Mumbai',
    phone: '+91 98765 43210',
    whatsapp: '+919876543210',
    email: 'info@spicyfeast.com',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&q=80&w=600',
    website: 'https://spicyfeast.com',
    description: 'A genuine North Indian and Mughlai specialty diner operating since 2012. Renowned for its buttery paneer delight, rich gravies, charcoal-grilled tandoori delicacies, and highly responsive family-oriented dining atmosphere.',
    tags: ['Punjabi', 'Fine Dine', 'Family Restaurant', 'Tandoori', 'Biryani'],
    features: ['Air Conditioned', 'Home Delivery', 'Valet Parking', 'Accepts Credit Cards', 'Pure Veg Option'],
    timing: 'Open • Closes 11:30 PM',
    verificationStatus: 'premium',
    lat: 35,
    lng: 40,
    reviews: [
      { id: 'r1_1', username: 'Rajesh Kumar', rating: 5, text: 'Absolutely spectacular butter chicken and garlic naan! The service was swift and the vibes were delightful.', date: '2026-05-18' },
      { id: 'r1_2', username: 'Sneha Patel', rating: 4, text: 'Great vegetarian choices. Paneer Tikka was beautifully smoky. Mildly crowded on weekends, reservation recommended.', date: '2026-05-30' },
      { id: 'r1_3', username: 'Amit Sharma', rating: 5, text: 'Authentic taste index, pocket-friendly pricing on combos, and remarkably friendly team.', date: '2026-06-02' }
    ]
  },
  {
    id: 'b2',
    name: 'Royal Heritage Dental Clinic',
    category: 'doctors',
    rating: 4.9,
    reviewsCount: 88,
    address: 'Flat 201, Green Glen Layout, Outer Ring Road',
    area: 'Bellandur',
    city: 'Bengaluru',
    phone: '+91 80412 34567',
    whatsapp: '+918041234567',
    email: 'contact@royalheritagedental.com',
    image: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&q=80&w=600',
    website: 'https://royalheritagedental.com',
    description: 'Led by premium restorative dentists. Specializing in advanced orthodontics, pain-free root canals, laser teeth whitening, pediatric dentistry, and computer-guided dental implants utilizing top-tier international hygiene protocols.',
    tags: ['Dentist', 'Orthodontist', 'Dental Implant', 'Root Canal', 'Teeth Whitening'],
    features: ['Air Conditioned', 'Wheelchair Accessible', 'Prior Appointment Compulsory', 'Digital Payments Accepted'],
    timing: 'Open • Closes 8:00 PM',
    verificationStatus: 'verified',
    lat: 45,
    lng: 55,
    reviews: [
      { id: 'r2_1', username: 'Vikram Joshi', rating: 5, text: 'Completely painless root canal surgery! Dr. Ananya is extremely patient and explains everything clearly. Highly satisfied.', date: '2026-04-12' },
      { id: 'r2_2', username: 'Megha Rao', rating: 5, text: 'Very hygienic facility. Follows strict sanitization rules. Staff is polite. Five stars!', date: '2026-05-15' }
    ]
  },
  {
    id: 'b3',
    name: 'Apex Plumbing Services',
    category: 'plumbers',
    rating: 4.7,
    reviewsCount: 204,
    address: 'Block E, Sector 62',
    area: 'Noida Sector 62',
    city: 'Delhi',
    phone: '+91 99100 88223',
    whatsapp: '+919910088223',
    email: 'service@apexplumbing.co.in',
    image: 'https://images.unsplash.com/photo-1542013936693-8848e5740a9a?auto=format&fit=crop&q=80&w=600',
    description: 'Instant residential, commercial and industrial plumbing solvers. Offering water leak detection, sewer line flushing, high-end bathroom fittings installation, geyser maintenance, and 24/7 critical burst pipe emergency response.',
    tags: ['Plumber', 'Leak Repair', 'Bathroom Renovation', 'Drain Cleaning', 'Geyser Service'],
    features: ['Emergency Support 24/7', 'Verified Technicians', 'Warranty on Repairs', 'Transparent Estimations'],
    timing: 'Open • Closes 9:00 PM',
    verificationStatus: 'verified',
    lat: 60,
    lng: 30,
    reviews: [
      { id: 'r3_1', username: 'Harsh Vardhan', rating: 5, text: 'Called them for kitchen sink leakage at night. Plumber arrived inside 30 mins and fixed it masterfully. Fair rates.', date: '2026-05-25' },
      { id: 'r3_2', username: 'Deepak Chawla', rating: 4, text: 'Good quality workmanship. Installed all my bathroom fixtures nicely during house shifting.', date: '2026-06-01' }
    ]
  },
  {
    id: 'b4',
    name: 'The Grand Palace Resort',
    category: 'hotels',
    rating: 4.6,
    reviewsCount: 312,
    address: '15, Sardar Patel Marg, near Diplomatic Enclave',
    area: 'Chanakyapuri',
    city: 'Delhi',
    phone: '+91 11445 56677',
    email: 'reservations@grandpalacedelhi.com',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80&w=600',
    website: 'https://grandpalacedelhi.com',
    description: 'An elegant oasis blending heritage architecture with modern conveniences. Boasting spacious luxury suites, standard temperature-controlled swimming pool, fine-dine multi-cuisine gardens, multi-tiered business halls, and exemplary concierge services.',
    tags: ['Luxury Hotel', 'Resort', 'Business Suites', 'Banquet Hall', 'Staycation'],
    features: ['Free WiFi', 'Swimming Pool', 'Fitness Center', 'In-house Bar', '24-hour Room Service', 'Free Breakfast'],
    timing: 'Open • 24 Hours',
    verificationStatus: 'premium',
    lat: 50,
    lng: 25,
    reviews: [
      { id: 'r4_1', username: 'Karan Mehra', rating: 5, text: 'Absolutely spectacular. Loved the lavish breakfast spread and deep royal aesthetics. Perfect place for luxury leisure.', date: '2026-05-10' },
      { id: 'r4_2', username: 'Rohan Malhotra', rating: 4, text: 'Extremely professional hospitality. Ideal business meet hosting. A little pricey but completely worth it.', date: '2026-05-20' }
    ]
  },
  {
    id: 'b5',
    name: 'Glow Up Hair & Beauty Salon',
    category: 'salons',
    rating: 4.5,
    reviewsCount: 165,
    address: 'Plot 4, Khader Nawaz Khan Road, Nungambakkam',
    area: 'Nungambakkam',
    city: 'Chennai',
    phone: '+91 44282 31923',
    whatsapp: '+919176001234',
    image: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&q=80&w=600',
    description: 'Premier fashion destination specializing in trending global hair styling techniques (balayage, keratin smoothing), luxurious organic bridal facials, therapeutic head massages, microblading, and custom gel nail art.',
    tags: ['Beauty Parlour', 'Hair Salon', 'Bridal Makeup', 'Manicure', 'Spa'],
    features: ['Air Conditioned', 'Women-only Hours Available', 'Valet Parking', 'Prior Booking Suggested'],
    timing: 'Open • Closes 9:00 PM',
    verificationStatus: 'verified',
    lat: 38,
    lng: 78,
    reviews: [
      { id: 'r5_1', username: 'Priya Sundaram', rating: 5, text: 'Loved my hair balayage! The stylist really understood what I wanted. Highly recommended for premium hair coloring.', date: '2026-05-04' },
      { id: 'r5_2', username: 'Janani R', rating: 4, text: 'Hygienic manicure and facial. The staff is well-behaved, though on weekends there is a 20-minute waiting time.', date: '2026-05-22' }
    ]
  },
  {
    id: 'b6',
    name: 'Iron Temple Gymnasium',
    category: 'gyms',
    rating: 4.8,
    reviewsCount: 110,
    address: '4th Floor, Signature Tower, Jubilee Hills Road No. 36',
    area: 'Jubilee Hills',
    city: 'Hyderabad',
    phone: '+91 90001 22334',
    email: 'membership@irontemplefitness.com',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=600',
    website: 'https://irontemplefitness.com',
    description: 'State-of-the-art strength and cardio layout. Spanning 10,000 sq ft, offering hammer strength machines, powerlifting platforms, high-intensity functional turf, certified personal training coaches, nutrition planning, and steam bath recovery.',
    tags: ['Gym', 'Fitness Trainer', 'Cardio', 'Zumba Classes', 'Crossfit'],
    features: ['Personal Trainers', 'Locker Room & Showers', 'Steam Room', 'Air Conditioned', 'Free Trials'],
    timing: 'Open • Closes 10:00 PM',
    verificationStatus: 'premium',
    lat: 44,
    lng: 66,
    reviews: [
      { id: 'r6_1', username: 'Nikhil Reddy', rating: 5, text: 'Easily the best-equipped gym in Hyderabad. Trainers actually guide you throughout, unlike other commercial fitness centers.', date: '2026-05-15' },
      { id: 'r6_2', username: 'Sravya T', rating: 5, text: 'Very energetic atmosphere, clean changing rooms, and friendly crowd. Highly motivating music playlists!', date: '2026-06-03' }
    ]
  },
  {
    id: 'b7',
    name: 'Smart Minds International School',
    category: 'education',
    rating: 4.7,
    reviewsCount: 95,
    address: 'Survey No. 88, Viman Nagar High Street',
    area: 'Viman Nagar',
    city: 'Pune',
    phone: '+91 20260 55123',
    email: 'admissions@smartmindsschool.edu.in',
    image: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?auto=format&fit=crop&q=80&w=600',
    description: 'A futuristic co-educational institution following CBSE curriculum. Offering inquiry-based learning models, world-class stem laboratories, computer labs, vast open sports courtyards, smart classrooms, and personalized leadership coaching modules.',
    tags: ['CBSE School', 'Play School', 'High School', 'STEM Education', 'Daycare'],
    features: ['School Bus Transport', 'Playground', 'Smart Board Classrooms', 'CCTV Secured Campus', 'Indoor Sports Hall'],
    timing: 'Closed • Opens Monday 8:00 AM',
    isClosed: true,
    verificationStatus: 'premium',
    lat: 42,
    lng: 48,
    reviews: [
      { id: 'r7_1', username: 'Prashant G', rating: 5, text: 'Exceptional teaching staff. My daughter has blossomed in confidence and academics. Highly interactive child learning.', date: '2026-04-30' },
      { id: 'r7_2', username: 'Aditi Deshpande', rating: 4, text: 'Great infrastructure, vast sports facilities and responsive principal directory. Admission procedure is quite rigorous though.', date: '2026-05-17' }
    ]
  },
  {
    id: 'b8',
    name: 'SafeMove Packers & Movers',
    category: 'packers',
    rating: 4.9,
    reviewsCount: 318,
    address: 'G-18, Sector 4, Salt Lake City',
    area: 'Salt Lake',
    city: 'Kolkata',
    phone: '+91 93300 44556',
    whatsapp: '+919330044556',
    image: 'https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?auto=format&fit=crop&q=80&w=600',
    description: 'ISO-Certified shifting specialists since 2008. Flawless execution across household relocation, luxury car shifting, office machinery shipping, heavy-weight industrial transitions with secure multi-layered bubble wrapping and full transit insurance.',
    tags: ['Packers and Movers', 'House Shifting', 'Car Relocation', 'Office Moving', 'Commercial Packers'],
    features: ['Transit Insurance', 'Free Estimations', 'GPS Tracked Vehicles', 'Bubble Wrapping Service', '24/7 Helpline'],
    timing: 'Open • Closes 8:30 PM',
    verificationStatus: 'premium',
    lat: 78,
    lng: 42,
    reviews: [
      { id: 'r8_1', username: 'Anirban Sen', rating: 5, text: 'Extremely professional group. Shifted my entire 3 BHK from Salt Lake to Garia without a single line / scratch. Smooth handling!', date: '2026-05-23' },
      { id: 'r8_2', username: 'Rumpa Banerjee', rating: 5, text: 'Polite laborers, rapid packing index, completely transparent bills with zero hidden levies. Strongly recommended!', date: '2026-05-28' }
    ]
  },
  {
    id: 'b9',
    name: 'GoRide Rent-a-Car',
    category: 'rentals',
    rating: 4.4,
    reviewsCount: 74,
    address: 'Near Terminal 1, Domestic Airport Area',
    area: 'Vile Parle',
    city: 'Mumbai',
    phone: '+91 98222 11440',
    whatsapp: '+919822211440',
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=600',
    website: 'https://goridecars.in',
    description: 'A wide, pristine fleet of vehicles ranging from sleek budget hatchbacks, executive sedans, spacious multi-seater SUVs (Innova Crysta, Scorpio-N) to premium luxury sports cars. Self-drive options as well as clean, background-verified uniformed chauffeurs.',
    tags: ['Car Rental', 'Self Drive Cars', 'Airport Taxi Service', 'SUV Hire', 'Chauffeur Driven'],
    features: ['Self-drive Option', 'Unlimited Kilometers Plan', 'Clean & Sanitized Fleet', 'No Hidden Deposit', 'In-transit RSA Support'],
    timing: 'Open • 24 Hours',
    verificationStatus: 'verified',
    lat: 32,
    lng: 38,
    reviews: [
      { id: 'r9_1', username: 'Sanjeev Nair', rating: 5, text: 'Rented an Thar for long weekend drive. Seamless paperwork, clean car, perfectly working mechanics. Extremely happy with self-pickup.', date: '2026-05-12' },
      { id: 'r9_2', username: 'Rohan Deshmukh', rating: 4, text: 'Prompt airport pickup and dropping. Drivers are well-acquainted with Mumbai short-cuts. Fair rates.', date: '2026-05-19' }
    ]
  },
  {
    id: 'b10',
    name: 'Elite Care General Hospital',
    category: 'hospitals',
    rating: 4.8,
    reviewsCount: 215,
    address: 'Avenue Road, Near Terminal 2, Sakinaka',
    area: 'Andheri East',
    city: 'Mumbai',
    phone: '+91 98900 11223',
    whatsapp: '+919890011223',
    email: 'info@elitecarehospital.com',
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=600',
    website: 'https://elitecarehospital.com',
    description: 'Super-Speciality hospital with 250 beds, offering continuous emergency services, high-tech cardiothoracic theatres, dedicated intensive care units, 3D sonographic scan bays, and leading diagnostic laboratories.',
    tags: ['Hospital', 'Emergency ICU', 'MRI Scan', 'Cardiology', 'Pediatric ward'],
    features: ['Emergency Room 24x7', 'Blood Bank on board', 'Ambulance service', 'Cashless TPA Claim', 'Inhouse Pharmacy'],
    timing: 'Open • 24 Hours',
    verificationStatus: 'premium',
    lat: 41,
    lng: 41,
    reviews: [
      { id: 'r10_1', username: 'Aravind Swamy', rating: 5, text: 'Very modern hospital. Best trauma response staff and clean restrooms. Handled our family emergency with extreme professionalism.', date: '2026-04-19' },
      { id: 'r10_2', username: 'Nisha G.', rating: 4, text: 'Excellent doctors, diagnostic reports are delivered on phone via SMS. Highly trusted.', date: '2026-05-02' }
    ]
  },
  {
    id: 'b11',
    name: 'ProShield Pest Control & Sanitization',
    category: 'pest-control',
    rating: 4.9,
    reviewsCount: 167,
    address: 'D-32, Connaught Circus, near Rajiv Chowk Metro',
    area: 'Connaught Place',
    city: 'Delhi',
    phone: '+91 99555 60601',
    whatsapp: '+919955560601',
    email: 'help@proshieldpest.com',
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&q=80&w=600',
    description: 'Eco-safe organic pest termination agency. Specialized in deep termite drilling barriers, odor-free cockroach gel injection, mosquito control fogging, residential rodent traps, and comprehensive sanitization shields with safe herbal derivatives.',
    tags: ['Pest Control', 'Termite Treatment', 'Bedbugs Spray', 'Cockroach Gel', 'Sanitization'],
    features: ['Odorless Herbal Spray', 'Government Certified Technicians', 'Up to 2 Years Warranty', 'Free Retreatment Policy'],
    timing: 'Open • Closes 7:00 PM',
    verificationStatus: 'premium',
    lat: 52,
    lng: 18,
    reviews: [
      { id: 'r11_1', username: 'Rahul Rastogi', rating: 5, text: 'Did termite treatment in my flat. Zero mess, zero smell, and they gave a 3-year warranty card. Extremely satisfied!', date: '2026-05-15' },
      { id: 'r11_2', username: 'Kirti Sen', rating: 5, text: 'Fabulous results. The cockroach population in our kitchen vanished inside 3 days. Highly recommended!', date: '2026-06-05' }
    ]
  },
  {
    id: 'b12',
    name: 'Nexus Electronics Mega-Mall',
    category: 'electronics',
    rating: 4.7,
    reviewsCount: 145,
    address: 'Store No. 5-7, SP Road, Electronic City',
    area: 'Electronic City',
    city: 'Bengaluru',
    phone: '+91 80222 33344',
    whatsapp: '+918022233344',
    email: 'sales@nexuselectronics.co.in',
    image: 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?auto=format&fit=crop&q=80&w=600',
    website: 'https://nexuselectronics.co.in',
    description: 'An expansive modern electronics showroom showcasing a vast catalog of top-shelf premium OLED Smart TVs, laptops, dynamic digital cameras, heavy kitchen appliances, home theaters, and gaming consoles with official brand warranties.',
    tags: ['Electronics Showroom', 'Laptops Shop', 'Smart TVs', 'Kitchen Appliances', 'Mobile Phones'],
    features: ['No Cost EMI Schemes', 'Free Same-Day Delivery', 'Official Brand Partner', 'Extended Care Plans', 'Tech Demo counter'],
    timing: 'Open • Closes 9:30 PM',
    verificationStatus: 'verified',
    lat: 50,
    lng: 58,
    reviews: [
      { id: 'r12_1', username: 'Pranam Reddy', rating: 5, text: 'Got an OLED TV with massive discount on exchange! Quick wall assembly, very courteous support staff.', date: '2026-05-10' },
      { id: 'r12_2', username: 'Ananya S.', rating: 4, text: 'Great place for tech enthusiasts. Laptop experience zone is wonderful. Prices are matching online rates.', date: '2026-05-24' }
    ]
  },
  {
    id: 'b13',
    name: 'Golden Gate Multi-Cuisine Dine',
    category: 'restaurants',
    rating: 4.6,
    reviewsCount: 89,
    address: 'No 45, 100 Feet Road, Indiranagar',
    area: 'Indiranagar',
    city: 'Bengaluru',
    phone: '+91 80499 11990',
    image: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&q=80&w=600',
    description: 'Premier culinary haven for global multi-cuisine treats. Featuring freshly roasted clay-oven kebabs, authentic hand-tossed classic woodfired pizzas, premium sushi setups, custom mocktails, and live acoustic violin on weekends.',
    tags: ['Italian Pizza', 'Sushi Bar', 'Global Dining', 'Rooftop Cafe', 'Indiranagar Eatout'],
    features: ['Rooftop Seating', 'Live Music', 'Serves Alcohol', 'Valet Parking', 'Kids Play Area'],
    timing: 'Open • Closes 12:00 AM',
    verificationStatus: 'premium',
    lat: 48,
    lng: 62,
    reviews: [
      { id: 'r13_1', username: 'Sid M.', rating: 5, text: 'Stunning environment, the wood-fired pizza reminds me of Rome. Exceptional multi dining!', date: '2026-05-11' }
    ]
  },
  {
    id: 'b14',
    name: 'Fortis Care Multispeciality Hospital',
    category: 'hospitals',
    rating: 4.9,
    reviewsCount: 382,
    address: 'Sector 4, Rohini High Avenue',
    area: 'Rohini',
    city: 'Delhi',
    phone: '+91 11499 88811',
    image: 'https://images.unsplash.com/photo-1586773860418-d3b320281b3c?auto=format&fit=crop&q=80&w=600',
    description: 'State-certified elite tertiary healthcare facility featuring dedicated expert panel oncologists, neurological trauma emergency wings, high-precision robotic surgery, joint replacement specialists, and world-class inpatient suites.',
    tags: ['Tertiary care', 'Robotic Surgery', 'Oncology Care', 'ICU Emergency', 'Dialysis Unit'],
    features: ['Robotic surgery center', 'Standard Emergency 24x7', 'Heli-evacuation support', 'Premium private rooms', 'TPA Cashless support'],
    timing: 'Open • 24 Hours',
    verificationStatus: 'premium',
    lat: 62,
    lng: 22,
    reviews: [
      { id: 'r14_1', username: 'Sunildutt Sharma', rating: 5, text: 'We received spectacular joint replacement therapy for our father here. Very smooth rehabilitation processes.', date: '2026-05-18' }
    ]
  },
  {
    id: 'b15',
    name: 'Shanti Wellness Yoga & Gym',
    category: 'gyms',
    rating: 4.8,
    reviewsCount: 104,
    address: 'C-2, Koregaon Park Plaza, Lane No. 5',
    area: 'Koregaon Park',
    city: 'Pune',
    phone: '+91 20299 44112',
    image: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?auto=format&fit=crop&q=80&w=600',
    description: 'An exquisite wellness temple blending modern heavy resistance weight gyms with hot yoga chambers, state-of-the-art Pilates reformer frames, calming meditation pools, and personalized raw organic custom juices.',
    tags: ['Hot Yoga', 'Strengths Gym', 'Meditation Center', 'Pilates Reformer', 'Weight Loss'],
    features: ['Premium Yoga Studios', 'Certified Pilates Coaches', 'Steam Bath Chambers', 'In-house Dietician', 'Vast Car Parking'],
    timing: 'Open • Closes 9:30 PM',
    verificationStatus: 'verified',
    lat: 41,
    lng: 50,
    reviews: [
      { id: 'r15_1', username: 'Rohan N.', rating: 5, text: 'Mindboggling experience. Clean, ultra-private, and the Pilates trainers are globally certified.', date: '2026-05-20' }
    ]
  },
  {
    id: 'b16',
    name: 'Croma Direct Digital Electronics',
    category: 'electronics',
    rating: 4.6,
    reviewsCount: 198,
    address: 'Multiplex Building, Linking Road, Khar West',
    area: 'Khar West',
    city: 'Mumbai',
    phone: '+91 99000 11222',
    whatsapp: '+919900011222',
    image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&q=80&w=600',
    website: 'https://croma.com',
    description: 'Your premier digital companion. Offering a wide range of top smartphones, custom laptops, heavy washing machines, side-by-side refrigerators, air conditioners, soundbars, and grooming accessories directly from manufacturers.',
    tags: ['Smartphones', 'Washing Machines', 'Apple Reseller', 'LED Televisions', 'Electronics Outlet'],
    features: ['Authorized Apple partner', 'Assured Cashback options', 'Express home setup', 'Finance and EMIs provided', 'Live test models'],
    timing: 'Open • Closes 10:00 PM',
    verificationStatus: 'premium',
    lat: 34,
    lng: 39,
    reviews: [
      { id: 'r16_1', username: 'Vandana S.', rating: 5, text: 'Bought the latest iPhone here. Got an instant bank rebate, and the executive transferred my data on the spot within 20 mins!', date: '2026-05-25' }
    ]
  },
  {
    id: 'b17',
    name: 'St. Jude International Academy',
    category: 'education',
    rating: 4.8,
    reviewsCount: 121,
    address: 'School Lane, Juhu Tara Road, Juhu',
    area: 'Juhu',
    city: 'Mumbai',
    phone: '+91 22261 54321',
    image: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=600',
    description: 'An elite institution presenting the Cambridge IGCSE and IB curriculum path. Designed to grow creative critical thought, featuring global student exchange, robotic clubs, Olympic-sized swimming arenas, and extensive fine-arts centers.',
    tags: ['IB Board School', 'International Academy', 'IGCSE Course', 'Robotics Classes', 'Sports coaching'],
    features: ['Olympic Swimming Pool', 'Interactive smart pods', 'Vast science research labs', 'AC school transit', 'Secured entry points'],
    timing: 'Closed • Opens Monday 8:00 AM',
    isClosed: true,
    verificationStatus: 'premium',
    lat: 36,
    lng: 36,
    reviews: [
      { id: 'r17_1', username: 'Farhan Contractor', rating: 5, text: 'Stunning development curriculum! Our child feels extremely motivated. Highly premium academic framework.', date: '2026-05-30' }
    ]
  },
  {
    id: 'b18',
    name: 'Elite Pest Solution Services',
    category: 'pest-control',
    rating: 4.7,
    reviewsCount: 110,
    address: 'Office 402, Signature Plaza, S.V. Road',
    area: 'Bandra West',
    city: 'Mumbai',
    phone: '+91 98800 55660',
    whatsapp: '+919880055660',
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&q=80&w=600',
    description: 'Rapid-action pest, termite, and rodent controllers. Operating with WHO-certified safe chemical sprays, odorless heat treatments, anti-cockroach gel matrices, and eco-friendly organic wooden shield barriers for elegant home interiors.',
    tags: ['Bandra Pest Control', 'Wood termite sprays', 'Pest eradication', 'Odorless kitchen gel', 'Rat traps'],
    features: ['WHO-approved chemicals', 'Odorless operations', 'Same-day home sanitarty', 'Free post-review audit', '100% money back guarantee'],
    timing: 'Open • Closes 8:00 PM',
    verificationStatus: 'verified',
    lat: 33,
    lng: 42,
    reviews: [
      { id: 'r18_1', username: 'Haris Khan', rating: 5, text: 'Cleared our huge bedbug problem within single chemical session. High performance. Courteous team.', date: '2026-05-14' }
    ]
  },
  {
    id: 'b19',
    name: 'QuickFix Plumbing & Leak Experts',
    category: 'plumbers',
    rating: 4.8,
    reviewsCount: 95,
    address: 'Shops Complex, near Juhu Circle',
    area: 'Juhu',
    city: 'Mumbai',
    phone: '+91 97700 88990',
    whatsapp: '+919770088990',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&q=80&w=600',
    description: 'Your reliable neighborhood technician team. Offering elite laser leak location scans, pipeline installations, high-pressure unclog treatments, electronic geyser repairs, and luxury multi-nozzle jet shower setups.',
    tags: ['Water leak scan', 'Luxury plumbing', 'Geyser replacements', 'Kitchen drainage', 'Urgent plumber'],
    features: ['Emergency 24 hr dispatch', 'Fix inside 45 Mins', 'Warranty proof bills', 'Certified plumbing license'],
    timing: 'Open • 24 Hours',
    verificationStatus: 'premium',
    lat: 35,
    lng: 35,
    reviews: [
      { id: 'r19_1', username: 'Geeta Shroff', rating: 5, text: 'Outstanding precision. Mastered the complex shower control leakage that multiple plumbers couldn\'t diagnose. Elite standards.', date: '2026-06-04' }
    ]
  },
  {
    id: 'b20',
    name: 'Hilton Garden Premium Suite',
    category: 'hotels',
    rating: 4.8,
    reviewsCount: 290,
    address: 'LBS Marg, Landmark near Powai Lake Resort',
    area: 'Powai',
    city: 'Mumbai',
    phone: '+91 22669 88000',
    image: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&q=80&w=600',
    description: 'Enchanting luxury hotel looking out over pristine Powai Lake. Housing bespoke executive workspaces, open-air infinity pools, authentic Mediterranean dining hubs, massive banquet halls, and standard valet facilities.',
    tags: ['Powai luxury stay', 'Lakeview Suite', 'Corporate lounge', 'Infinity pool', 'High-end Dining'],
    features: ['Lake Frontage balcony', 'Infinity SkyPool', 'Complimentary WiFi', 'Tastiest Buffet spread', 'Valet parking', 'Round-the-clock service'],
    timing: 'Open • 24 Hours',
    verificationStatus: 'premium',
    lat: 37,
    lng: 43,
    reviews: [
      { id: 'r20_1', username: 'Anurag Kashyap', rating: 5, text: 'Top drawer service levels. The lakefront views at sunset are breathtaking. Clean rooms with spacious workstation sections.', date: '2026-05-27' }
    ]
  },
  {
    id: 'b21',
    name: 'Oasis Medi-Spa & Beauty Clinic',
    category: 'salons',
    rating: 4.7,
    reviewsCount: 140,
    address: 'Plot 120, Carter Road Promenade',
    area: 'Bandra West',
    city: 'Mumbai',
    phone: '+91 22285 41920',
    whatsapp: '+919163000419',
    image: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&q=80&w=600',
    description: 'A sanctuary of luxurious holistic wellness. Specializing in standard chemical skin peels, gold collagen facials, Ayurvedic Swedish body massage therapy, hair botox, and standard acrylic nail customization workshops.',
    tags: ['Carter Road Salon', 'collagen facials', 'Swedish body rubs', 'Hair Botox booster', 'Gel extensions'],
    features: ['Sea View Lounge', 'Certified Dermatologist', 'Eco Natural cosmetics', 'Reserved lady slots'],
    timing: 'Open • Closes 9:30 PM',
    verificationStatus: 'premium',
    lat: 32,
    lng: 43,
    reviews: [
      { id: 'r21_1', username: 'Rhea Chakraborty', rating: 5, text: 'Most relaxing sea view massage. Absolute paradise in the city. The Swedish therapy relieved all my stress.', date: '2026-05-30' }
    ]
  },
  {
    id: 'b22',
    name: 'Dr. Mehta Pediatric & Cardiac Clinic',
    category: 'doctors',
    rating: 4.9,
    reviewsCount: 178,
    address: 'Chambers 101, Hughes Road, Near Opera House',
    area: 'South Mumbai',
    city: 'Mumbai',
    phone: '+91 22236 88990',
    whatsapp: '+919820054321',
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=600',
    description: 'Led by highly vetted Dr. Shrenik Mehta (MD Pediatrics) and Dr. Rita Mehta (DM Cardiology). Specializing in pediatric care immunizations, dynamic cardiac fitness stress tests, and computer-supported health audits.',
    tags: ['Pediatrician', 'Cardiologist', 'Opera House clinic', 'Child wellness', 'ECG tests'],
    features: ['Air Conditioned lounge', 'Prior slots booking', 'Highly safe nursery ward', 'Instant PDF medical reports'],
    timing: 'Open • Closes 7:30 PM',
    verificationStatus: 'premium',
    lat: 31,
    lng: 31,
    reviews: [
      { id: 'r22_1', username: 'Shaleen Vora', rating: 5, text: 'Dr. Rita Mehta is very systematic and spends lots of time clarifying diagnosis in detail. Highly qualified medical couple.', date: '2026-05-19' }
    ]
  },
  {
    id: 'b23',
    name: 'Rapid Movers & Packers India',
    category: 'packers',
    rating: 4.8,
    reviewsCount: 250,
    address: 'Warehouse Block D, Ghatkopar East Industrial Zone',
    area: 'Ghatkopar East',
    city: 'Mumbai',
    phone: '+91 98900 66778',
    whatsapp: '+919890066778',
    image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?auto=format&fit=crop&q=80&w=600',
    description: 'Highly professional, ISO-accredited packers. Offering dynamic packing, high-integrity transport container trucks, wooden crate packing for sensitive electronic goods, expert piano relocations, and transit damage insurance protection.',
    tags: ['Bandra cargo relocation', 'Flat shifting', 'Household crates', 'Car container transporters', 'Cargo warehouse'],
    features: ['Accredited ISO standard', 'GPS Location dispatch alerts', 'Complementary bubble covers', 'Written zero-brokerage quote'],
    timing: 'Open • Closes 9:00 PM',
    verificationStatus: 'verified',
    lat: 38,
    lng: 44,
    reviews: [
      { id: 'r23_1', username: 'Siddharth Roy', rating: 5, text: 'Remarkable shifting speed! They packed up our heavy 4 BHK inside 4 hours and transported it safely. Highly professional packers.', date: '2026-05-24' }
    ]
  },
  {
    id: 'b24',
    name: 'ZoomAuto Hatchback Rentals',
    category: 'rentals',
    rating: 4.6,
    reviewsCount: 110,
    address: 'Under Metro Pillar 42, Karol Bagh',
    area: 'Karol Bagh',
    city: 'Delhi',
    phone: '+91 99111 22330',
    whatsapp: '+919911122330',
    image: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=600',
    description: 'Affordable self-drive vehicle fleet centered in Delhi Karol Bagh. Offering flexible hatchbacks, diesel sedans, and high-clearance adventure vehicles. Clean vehicles, completely contactless smartphone pickups, and keyless rentals.',
    tags: [' Karol Bagh Self-Drive', 'Cheapest car hire', 'Rentals without security deposit', 'Automatic Hatchback', 'Self pick up'],
    features: ['Smartphone contactless unlocks', 'Full hybrid safety checked', 'Cheapest plans', 'All-India permit provided'],
    timing: 'Open • 24 Hours',
    verificationStatus: 'verified',
    lat: 58,
    lng: 26,
    reviews: [
      { id: 'r24_1', username: 'Navjot Singh', rating: 5, text: 'Superb contactless smartphone startup. Clean car, fully tanked, and absolute value for money!', date: '2026-05-21' }
    ]
  }
];
